namespace BlueFireRando;

partial class Randomiser
{
    readonly string[] FirstDoor = new string[]
    {
        "Chest_A01_TempleGardens_Ability_SpinAttack2",
        "Chest_A02_Keep_Loot_02",
        "Chest_A01_Keep_Shield",
        "Chest_A02_Keep_Key_01"
    };

    string[] checks =
    {
        "Items::NewEnumerator45",
        "Items::NewEnumerator72",
        "Items::NewEnumerator6",
        "Items::NewEnumerator24",
        "Abilities::NewEnumerator9",
        "Items::NewEnumerator72",
        "Items::NewEnumerator6",
        "Items::NewEnumerator24",
        "Items::NewEnumerator24",
        "Weapons::NewEnumerator10",
        "E_Emotes::NewEnumerator0",
        "Items::NewEnumerator6",
        "Items::NewEnumerator24",
        "Items::NewEnumerator24",
        "Items::NewEnumerator24",
        "Items::NewEnumerator31",
        "Spirits::NewEnumerator13",
        "Items::NewEnumerator17",
        "Items::NewEnumerator25",
        "Items::NewEnumerator31",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator24",
        "Items::NewEnumerator26",
        "Items::NewEnumerator31",
        "Tunics::NewEnumerator31",
        "Items::NewEnumerator7",
        "Items::NewEnumerator7",
        "Items::NewEnumerator7",
        "Items::NewEnumerator7",
        "Items::NewEnumerator7",
        "Items::NewEnumerator30",
        "Quests::NewEnumerator26",
        "Spirits::NewEnumerator0",
        "Items::NewEnumerator42",
        "Tunics::NewEnumerator15",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator55",
        "Weapons::NewEnumerator6",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Tunics::NewEnumerator2",
        "E_Emotes::NewEnumerator6",
        "E_Emotes::NewEnumerator7",
        "Items::NewEnumerator27",
        "Items::NewEnumerator70",
        "Items::NewEnumerator9",
        "Items::NewEnumerator9",
        "Items::NewEnumerator24",
        "Spirits::NewEnumerator4",
        "Tunics::NewEnumerator16",
        "Items::NewEnumerator46",
        "Tunics::NewEnumerator16",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator26",
        "Weapons::NewEnumerator8",
        "Spirits::NewEnumerator2",
        "Items::NewEnumerator25",
        "Abilities::NewEnumerator15",
        "Items::NewEnumerator6",
        "Items::NewEnumerator6",
        "Items::NewEnumerator6",
        "Items::NewEnumerator24",
        "Items::NewEnumerator31",
        "Spirits::NewEnumerator9",
        "Items::NewEnumerator6",
        "Items::NewEnumerator31",
        "Items::NewEnumerator31",
        "Items::NewEnumerator31",
        "Items::NewEnumerator31",
        "Weapons::NewEnumerator7",
        "Abilities::NewEnumerator1",
        "Items::NewEnumerator72",
        "Items::NewEnumerator72",
        "E_Emotes::NewEnumerator13",
        "E_Emotes::NewEnumerator8",
        "Items::NewEnumerator6",
        "Items::NewEnumerator72",
        "Tunics::NewEnumerator7",
        "E_Emotes::NewEnumerator4",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator31",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Abilities::NewEnumerator13",
        "Abilities::NewEnumerator14",
        "Items::NewEnumerator6",
        "E_Emotes::NewEnumerator2",
        "E_Emotes::NewEnumerator12",
        "Spirits::NewEnumerator3",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator80",
        "Items::NewEnumerator31",
        "Weapons::NewEnumerator2",
        "E_Emotes::NewEnumerator9",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "E_Emotes::NewEnumerator3",
        "Items::NewEnumerator42",
        "Items::NewEnumerator14",
        "Weapons::NewEnumerator1",
        "Items::NewEnumerator24",
        "Items::NewEnumerator25",
        "Items::NewEnumerator24",
        "Spirits::NewEnumerator21",
        "Items::NewEnumerator42",
        "Weapons::NewEnumerator4",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator54",
        "Items::NewEnumerator25",
        "E_Emotes::NewEnumerator11",
        "Spirits::NewEnumerator1",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "Items::NewEnumerator25",
        "E_Emotes::NewEnumerator5",
        "Spirits::NewEnumerator28",
        "Quests::NewEnumerator24",
        "Items::NewEnumerator81",
        "Items::NewEnumerator14",
        "Tunics::NewEnumerator14",
        "E_Emotes::NewEnumerator1",
        "Tunics::NewEnumerator10",
        "Items::NewEnumerator90",
        "Items::NewEnumerator90",
        "Items::NewEnumerator90",
        "Items::NewEnumerator90",
        "Items::NewEnumerator90",
        "Items::NewEnumerator90",
        "Items::NewEnumerator90",
        "Spirits::NewEnumerator12",
        "Spirits::NewEnumerator17",
        "Spirits::NewEnumerator25",
        "Items::NewEnumerator0",
        "Items::NewEnumerator83",
        "Items::NewEnumerator81",
        "Items::NewEnumerator80",
        "Items::NewEnumerator14",
        "Spirits::NewEnumerator10",
        "Spirits::NewEnumerator11",
        "Spirits::NewEnumerator7",
        "Spirits::NewEnumerator27",
        "Tunics::NewEnumerator27",
        "Tunics::NewEnumerator26",
        "Tunics::NewEnumerator25",
        "Tunics::NewEnumerator24",
        "Tunics::NewEnumerator23",
        "Tunics::NewEnumerator22",
        "Tunics::NewEnumerator21",
        "Tunics::NewEnumerator20",
        "Tunics::NewEnumerator19",
        "Tunics::NewEnumerator18",
        "Tunics::NewEnumerator17",
        "Spirits::NewEnumerator14",
        "Spirits::NewEnumerator15",
        "Weapons::NewEnumerator3",
        "Items::NewEnumerator91",
        "Items::NewEnumerator39",
        "Items::NewEnumerator89",
        "Items::NewEnumerator31",
        "Items::NewEnumerator25",
        "Items::NewEnumerator24"
    };

    void Randomise()
    {
        var rndm = new Random();
        //I love the Where syntax it's just...*chef's kiss*
        string[] checklist = checks.Where(check => Spirits.Checked && check[..7] == "Spirits" ||
                                                   Weapons.Checked && check[..7] == "Weapons" ||
                                                   Tunics.Checked && check[..6] == "Tunics" ||
                                                   Items.Checked && check[..5] == "Items" ||
                                                   Emotes.Checked && check[..8] == "E_Emotes" ||
                                                   Abilities.Checked && check[..9] == "Abilities").ToArray();
        //I'll just do randomising without logic for now because the thing is I want the new mixing to be tested first and foremost
        if (Spirits.Checked) RandoWithin(ref checklist, "Spirits");
        if (Emotes.Checked) RandoWithin(ref checklist, "E_Emotes");

        //basically everything else
        Queue<string> ChestChecks = new(checklist.Where(chestcheck => chestcheck[..7] == "Weapons" ||
                                                                                      chestcheck[..6] == "Tunics" ||
                                                                                      chestcheck[..5] == "Items" ||
                                                                                      chestcheck[..9] == "Abilities"));
        //codi's spirit that's in a chest
        if (Spirits.Checked) ChestChecks.Enqueue(checklist.Where(check => check[..7] == "Spirits").ToArray()[8]);
        ChestChecks = new(Helpers.Shuffle(ChestChecks));

        //TODO: writing these changes (they have been randomised in such a way that the order they are in is compatible with the order they are found in)
    }

    //for the ones which cannot mix (emote statues and spirits)
    void RandoWithin(ref string[] checklist, string enumref)
    {
        Queue<string> spirits = new(Helpers.Shuffle(checklist.Where(spirit => spirit[..enumref.Length] == enumref)));
        for (int i = 0; i < checklist.Length; i++) if (checklist[i][..enumref.Length] == enumref) checklist[i] = spirits.Dequeue();
    }

    char StringToEnum(string _enum) =>
        _enum.Split(':')[0] switch
        {
            "Items" => '0',
            "Weapons" => '1',
            "Tunics" => '2',
            "Spirits" => '3',
            "Abilities" => '6',
            "E_Emotes" => '7',
            _ => ' '
        };
    string GetName(string value) =>
        value.Split(':')[0] switch
        {
            "Items" => "Item",
            "Weapons" => "Weapon",
            "Tunics" => "Tunic",
            "Spirits" => "Amulet",
            "Abilities" => "Ability",
            "E_Emotes" => "Emote",
            _ => ""
        };

    enum InventoryItemType
    {
        Item = 0,
        Weapon = 1,
        Tunic = 2,
        Spirit = 3,
        Life = 4,
        SpiritSlot = 5,
        Ability = 6,
        Emote = 7,
    }
    enum E_Abilities
    {
        DoubleJump = 1,
        Dash = 2,
        Attack = 3,
        WallRun = 9,
        Sprint = 11,
        Spell = 13,
        Block = 14,
        SpinAttack = 15,
    }
    enum E_Emotes
    {
        Wave = 0,
        Applause = 1,
        Levitation = 2,
        Windmill = 3,
        HatKid = 4,
        Triceps = 5,
        Aggressive = 6,
        No = 7,
        Photo = 8,
        Celebration = 9,
        KungFu = 11,
        Techno = 12,
        Party = 13,
        Hello2 = 14,
        Empty = 15,
    }
    enum E_Items
    {
        LargePouch = 0,
        SmallPouch = 1,
        OldKey = 6,
        Book = 7,
        Rose = 9,
        Boot = 14,
        KinbankDebitCard = 15,
        IceCrystal = 17,
        SanctuaryStone = 18,
        RareKey = 19,
        PureShadowCatcher = 22,
        RubyOre = 24,
        SapphireOre = 25,
        DeadRat = 26,
        BremurPicture = 27,
        OddRock = 28,
        Souls = 29,
        SandRelic = 30,
        EmeraldOre = 31,
        ShadowFragment = 32,
        BlackFire = 33,
        AbyssPotion = 34,
        Coin = 35,
        VoidShards = 36,
        FireEssence = 39,
        ShadowPotion = 40,
        HolyBlessing = 41,
        Rice = 42,
        CarrotPotion = 44,
        Apple = 45,
        RottenApple = 46,
        Medicine = 47,
        SpiritCatcher = 49,
        HouseKey = 50,
        LifeElixir = 51,
        RoyalElixir = 52,
        BoulderPowder = 53,
        RareCheese = 54,
        SeagulSoup = 55,
        FleshEater = 56,
        ShardCluster = 57,
        ForestBug = 58,
        PoisonedPlant = 59,
        Dash = 61,
        DoubleJump = 62,
        SpinAttack = 63,
        WallRun = 64,
        FireBall = 65,
        DownSmash = 66,
        Shield = 67,
        SpiritSlot = 68,
        VoidKey = 69,
        Necklace = 70,
        KeyFireMaster = 71,
        KeyHolyMaster = 72,
        KeyIceMaster = 73,
        KeyDeathMaster = 74,
        KeyUthasTemple = 75,
        KeyGodMaster = 76,
        KeySteam = 77,
        KeyGraveyardKey = 78,
        HouseContract = 79,
        Mandoline = 80,
        RareGlasses = 81,
        RareSnow = 83,
        ComposerLetter = 84,
        Sprint = 85,
        BeiraVessel = 86,
        BeiraShards = 87,
        BasicPouch = 88,
        FireEssenceSlot = 89,
        VoidOre = 90,
        ExtraLargePouch = 91,
        Mana = 92,
        GuardianSoul = 93,
        CovenantSoul = 94,
        GuardianKey = 95,
        Duck = 96,
        RobiBadge = 97,
    }
    enum E_Spirits
    {
        FarasGrace = 0,
        HammerKing = 1,
        HolyCentry = 2,
        RiverSpirit = 3,
        AngryAmbusher = 4,
        SecretFruit = 5,
        MindController = 6,
        FrozenSoul = 7,
        HowlingTree = 8,
        LoveFlower = 9,
        StormCentry = 10,
        BloodPhantom = 11,
        PossesedBook = 12,
        ForestGuardian = 13,
        OnopSiblings = 14,
        MoiTheDreadful = 15,
        StoneHunter = 16,
        GoldenLust = 17,
        SpringWarrior = 18,
        CandleOnop = 19,
        StoneWarrior = 20,
        ToxicRat = 21,
        SummonedGod = 22,
        SummoningHand = 23,
        BettingHand = 24,
        LifeSteal = 25,
        ShadowDemon = 26,
        ShadowGru = 27,
        FlyingOnop = 28,
        ToxicWater = 29,
    }
    enum E_Weapons
    {
        DualBlades = 0,
        BloodstormBlades = 1,
        DiamondWings = 2,
        ShadowCasters = 3,
        EmberTwins = 4,
        IronJustice = 5,
        IceDestroyers = 6,
        PeaceKeepers = 7,
        SteelShanks = 8,
        BremurFamilySwords = 9,
        SilverBlades = 10,
        KinaDefenders = 11,
        Empty = 12,
        DLCVoidMaster = 13,
    }
}